FROM httpd:2.4
# COPY docker/apache/my-httpd.conf /usr/local/apache2/conf/httpd.conf

RUN apt-get update
RUN apt-get install -y apache2 apache2-dev
COPY docker/apache/my-vhosts.conf /usr/local/apache2/conf/extra/httpd-vhosts.conf
# COPY docker/apache/maps /usr/local/apache2/htdocs/maps

COPY  docker/apache/ldap.conf /usr/local/apache2/conf/ldap.conf
COPY  docker/apache/httpd.conf /usr/local/apache2/conf/httpd.conf
COPY  docker/apache/.htaccess /usr/local/apache2/htdocs/.htaccess
COPY  docker/apache/ca.crt /usr/local/apache2/conf/ca.crt