# Generated by Django 3.2.6 on 2021-10-01 14:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('lastLogin', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-lastLogin'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(null=True)),
                ('open_date', models.DateField(default=django.utils.timezone.now)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, verbose_name=True)),
                ('category', models.CharField(default='Support', max_length=20)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='core.profile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.profile')),
            ],
            options={
                'ordering': ['-open_date'],
            },
        ),
    ]
