# Generated by Django 3.2.6 on 2021-10-07 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=15)),
                ('ip', models.CharField(max_length=15)),
                ('switch_port', models.IntegerField(default=0)),
                ('vlan', models.IntegerField(default=0)),
                ('ram', models.IntegerField(default=0)),
                ('cpu', models.CharField(max_length=10)),
                ('hard_disk', models.CharField(max_length=10)),
                ('os', models.CharField(max_length=10)),
                ('mac', models.CharField(max_length=17)),
                ('model', models.CharField(max_length=20)),
                ('serial_num', models.CharField(max_length=17)),
                ('role', models.CharField(max_length=30)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
            ],
            options={
                'ordering': ['-host_name'],
            },
        ),
    ]
