# Generated by Django 3.2.6 on 2021-10-08 22:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), blank=True, null=True, size=None)),
                ('apps', models.ManyToManyField(blank=True, null=True, to='core.Category')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userpro', to='core.userprofile')),
            ],
        ),
    ]
